name:                getting-started
version:             0.1.0.0
github:              gerdreiss/learning-haskell
license:             BSD3
author:              Gerd Reiss
maintainer:          gerdreiss@jscriptive.com
copyright:           jscriptive.com

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/gerdreiss/learning-haskell#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.8.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  getting-started-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - getting-started
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  getting-started-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - getting-started
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
