name:                stoquodata
version:             0.1.0.0
github:              "gerdreiss/stoquodata"
license:             BSD3
author:              "Gerd Reiss"
maintainer:          "gerdreiss@jscriptive.com"
copyright:           "free"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gerdreiss/stoquodata#readme>

dependencies:
- base >= 4.7 && < 5
- fixed
- text
- time
- fmt
- Chart
- Chart-diagrams
- cassava
- optparse-applicative
- bytestring
- safe

library:
  source-dirs: src

executables:
  stoquodata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stoquodata

tests:
  stoquodata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stoquodata
