name:                dicegame
version:             0.1.0.0
github:              "gerdreiss/dicegame"
license:             BSD3
author:              "Gerd Reiss"
maintainer:          "gerdreiss@jscriptive.com"
copyright:           "free"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gerdreiss/dicegame#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- random

library:
  source-dirs: src

executables:
  dicegame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dicegame

tests:
  dicegame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dicegame
