name:                pgmparser
version:             0.1.0.0
github:              "gerdreiss/pgmparser"
license:             BSD3
author:              "Gerd Reiss"
maintainer:          "gerdreiss@jscriptive.com"
copyright:           "jscriptive.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Dev

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gerdreiss/pgmparser#readme>

dependencies:
- base
- bytestring

library:
  source-dirs: src

executables:
  pgmparser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pgmparser

tests:
  pgmparser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pgmparser
