name:                hauth
version:             0.1.0.0
github:              "gerdreiss/hauth"
license:             BSD3
author:              "Gerd Reiss"
maintainer:          "gerd@reiss.pro"
copyright:           "Gerd Reiss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/gerdreiss/learning-haskell/blob/master/PWDWH/hauth/README.md>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- aeson
- data-has
- katip
- exceptions
- mtl
- pcre-heavy # install pcre pkg-config on macos
- postgresql-simple # install postgresql on macos
- postgresql-simple-migration # install postgresql on macos
- resource-pool
- string-random
- template-haskell
- time
- time-lens

default-extensions:
- ConstraintKinds
- FlexibleContexts
- GeneralizedNewtypeDeriving
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- TemplateHaskell

library:
  source-dirs: src

executables:
  hauth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth

tests:
  hauth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth
